### ISSUE TITLE
BTP portal--old projects

### ISSUE THREAD

**Issue by sanjukta-chakraborty** [subhash011/Project-Allocation#36]
Hello
I am the BTP coordinator from Civil, I need some help with the BTP portal.

Is there any way to archive the projects already conducted in the last year. Instead, new projects will be mixed up with old projects and there may be confusion during the allocation. 

Another way is to request the faculties to delete their old projects and add new projects for the fresh allocation for the current fourth year. 

May I request you to help me in this regard if possible.

Sanjukta Chakraborty, PhD
Assistant Professor
Civil Engineering
IIT Palakkad

**Comment by Vamsi995** [comment]
As of now the only way of removing projects is the faculty removing their respective projects. We will look into adding a project deleting feature into the co-ordinator page.
